### ISSUE TITLE
Auto-magic using the Injector?

### ISSUE THREAD

**Issue by swaibar** [fromholdio/silverstripe-minigridfield#3]
What would be wonderful is if this was Auto-magically injected and replaces Gridfield universally and consistently, maybe using https://docs.silverstripe.org/en/4/developer_guides/extending/injector/#injector like this:

```
SilverStripe\Core\Injector\Injector:
  GridField:
    class: Fromholdio\MiniGridField\Forms\MiniGridField
```

**Comment by dizzystuff** [comment]
@swaibar I generally prefer to not do this kind of whole-sale replacement in the module by default, erring on the side of allowing devs to decide on a per-project basis to apply that kind of config or not. For this particular module, TBH it's quite rare on this end for us to replace all instances of grid field with this mini version, I'm not sure it'll make sense for all projects to do that OOTB. I will add the injection example to the readme though, is that a satisfactory compromise? 🙂

**Comment by dizzystuff** [comment]
Have updated the readme here: https://github.com/fromholdio/silverstripe-minigridfield#replacing-gridfield-universally

**Comment by swaibar** [comment]
@dizzystuff thank you for adding some info.  I love ModelAdmin and SilverStripe being a "DMS" (data management system) but if it could be a little more compact in all cases it would be that much better for UI... but now time has passed I can see where this doesn't work for some cases and it's best suited in selected cases.  Thanks again for the module!
